# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

#[[main]]
#name = "Outsourcing"
#url = "outsourcing/"
#weight = 2

#[[main]]
#name = "Careers"
#url = "careers/"
#weight = 3

[[main]]
name = "Contact"
url = "contact/"
weight = 4


